export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS";
export const CLEAR_ITEM_SUCCESS = "CLEAR_ITEM_SUCCESS";
export const CLEAR_ALL_ITEMS = "CLEAR_ALL_ITEMS";

export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN";
export const CLOSE_CART_HIDDEN = "CLOSE_CART_HIDDEN";